export const ProxyActionType = {
    CONNECT: "CONNECT",
    SEND_MESSAGE: "SEND_MESSAGE",
    DISCONNECT: "DISCONNECT",
    SET_PROXY: "SET_PROXY",
    CLEAR_PROXY: "CLEAR_PROXY",
    PROXY_STATUS: "PROXY_STATUS",
    INJECT_SCRIPT: "INJECT_SCRIPT",
    BADGE_COUNT: "BADGE_COUNT",
    SET_PROXY_CONFIG: "SET_PROXY_CONFIG",
    CLEAR_PROXY_CONFIG: "CLEAR_PROXY_CONFIG",
    GET_PROXY_STATUS: "GET_PROXY_STATUS"
} as const;

export type ProxyActionType = typeof ProxyActionType[keyof typeof ProxyActionType];