export const ProxyActionType = {
    SET_PROXY_CONFIG: "SET_PROXY_CONFIG",
    CLEAR_PROXY_CONFIG: "CLEAR_PROXY_CONFIG",
    GET_PROXY_STATUS: "GET_PROXY_STATUS",
    CLEAR_PROXY_LOGS: "CLEAR_PROXY_LOGS",
    GET_PROXY_LOGS: "GET_PROXY_LOGS",
    GET_PROXY_CONFIGS: "GET_PROXY_CONFIGS",
    ADD_PROXY_CONFIG: "ADD_PROXY_CONFIG",
    UPDATE_PROXY_CONFIG: "UPDATE_PROXY_CONFIG",
    SWITCH_PROXY: "SWITCH_PROXY",
} as const;

export const ContentActionType = {
    PROXY_CONFIGS_UPDATED: "PROXY_CONFIGS_UPDATED",
    PROXY_STATUS_CHANGED: "PROXY_STATUS_CHANGED",
    TRIGGER_ADD_PROXY: "TRIGGER_ADD_PROXY",
}

export type ProxyActionType = typeof ProxyActionType[keyof typeof ProxyActionType];